name: mdfptools
channels:
    - omnia
    - rdkit
dependencies:
    # conda build dependencies
    - rdkit
    - cairo >=1.16
    - bson
    - openforcefield==0.5.0
    - mdtraj
    - pip:
      - nbsphinx_link
      - recommonmark
      - nbsphinx
      - numpydoc
