name: mdfptools
channels:
    - omnia
dependencies:
    # readthedocs dependencies
    - numpydoc
    - nbsphinx
    # conda build dependencies
    - rdkit
    - openforcefield
    - mdtraj
    - pip:
      - nbsphinx_link
      - recommonmark
