# Configuration file for molecular descriptor benchmarking platform

data:
  db_connection: "dbname=cs_mdfps user=cschiebroek host=lebanon"
  test_data_path: "data/OPERA_Naef_Stratified_Test.csv"

results:
  path: "results/"

models:
  xgboost:
    max_depth: 6
    n_estimators: 100
  random_forest:
    max_depth: 10
    n_estimators: 100
  lasso:
    alpha: 0.1
  knn:
    n_neighbors: 5
  pls:
    n_components: 10

descriptors:
  - RDKit
  - MDFP
  - MACCS
  - ECFP4


